buildVariable: true
category:
- SERIF
familyName: Noto Serif Yezidi
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifYezidi.designspace
